### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by rc0403** [xsxjtu/GPPNN#1]
您好，我是一个图像融合的初学者，我对您的工作非常感兴趣，我想向您请求一下您在论文的数据集部分（QuickBird、GaoFen以及Landsat），不知道您是否方便。我保证仅限个人学习使用，如果方便的话，我留下我的邮箱：3312256349@qq.com，冒昧打扰，十分抱歉。祝好！

**Comment by jqsun98** [comment]
请问您收到作者提供的数据（QuickBird、GaoFen-2和Landsat8）了吗？如果收到的话，可否发一份到我的邮箱：910640694@qq.com，也只是用于个人学习，麻烦了，谢谢！

**Comment by tamshawn** [comment]
你好，我也是最近在研究这个方向，请问这些数据集现在您收到了吗？如果收到了方便的话可以发一下我邮箱吗，我的邮箱是：tamshawn@163.com，谢谢您了！！

**Comment by tamshawn** [comment]
> 请问您收到作者提供的数据（QuickBird、GaoFen-2和Landsat8）了吗？如果收到的话，可否发一份到我的邮箱：[910640694@qq.com](mailto:910640694@qq.com)，也只是用于个人学习，麻烦了，谢谢！

**Comment by shuangxu96** [comment]
The data is not open access.
