### ISSUE TITLE
Why does my metric calculations give poor result?

### ISSUE THREAD

**Issue by busrauludag1** [xsxjtu/GPPNN#4]
Hi @shuangxu96,

Thanks a lot for your code sharing! 
I am running your **train_GPPNN.py** file on my machine and also Google Colab without changing anything (except savemath file directory according to my computer OS's directory character). Unfortunately, I am finding very poor metric results like in figure. I couldn't find why.

<img width="422" alt="gppnn result" src="https://user-images.githubusercontent.com/51692429/196006409-94f252f8-c6cf-40c4-b7c3-6b93b4088705.png">

My another question is 'Why you use **Landsat8_train.h5** file for training data in your code but don't use **Landsat8_5.mat** file? Are there any differences between them? 

If you answer me, I will be very glad.
Thanks in advance.

**Comment by shuangxu96** [comment]
In this respository, the data only contains one training sample for evaluation the correctness of this code.
I suggest you to prepare your dataset with massive samples.
